In [1]:
import sys
import numpy as np

In [2]:
A = np.matrix([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]]);A

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [3]:
B = np.matrix([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]]);B

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [4]:
np.dot(A,B)

matrix([[ 34,  44,  54,  64],
        [ 82, 108, 134, 160],
        [ 34,  44,  54,  64],
        [ 82, 108, 134, 160]])